### ISSUE TITLE
Fix wasm bindings JS examples

### ISSUE THREAD

**Issue by sobolev-alexey** [iotaledger/streams#83]
On `chrysalis-2` branch proceed to the [bindings/wasm](https://github.com/iotaledger/streams/tree/chrysalis-2/bindings/wasm) folder, install packages, build project, then run files from the **examples** folder

Errors:

1. Node example:
```
$ node examples/node.js
const greet = streams.Greet()
                      ^
TypeError: streams.Greet is not a function
```

2. Web example
```
$ examples/web.js
channel address:  04dd1a92ec6c6bea1e8290e24676e387f6092aeeafb108cf9ccdb00272f0b1610000000000000000
multi branching:  false
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "builder error: JsValue(ReferenceError: Headers is not defined
ReferenceError: Headers is not defined
    at /streams/bindings/wasm/wasm-node/iota_streams_wasm.js:1304:15
    at /streams/bindings/wasm/wasm-node/iota_streams_wasm.js:214:22
    at <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha76d20b57f128831 (<anonymous>:wasm-function[110]:0x4a676))".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by iuslkae** [comment]
At the moment the right way to import the wasm file in nodejs requires to polyfill the fetch api from web.
like so:
```js
import fetch from 'node-fetch';

// @ts-ignore
global.fetch = fetch;
// @ts-ignore
global.Headers = fetch.Headers;
// @ts-ignore
global.Request = fetch.Request;
// @ts-ignore
global.Response = fetch.Response;
```
I runned the examples and they work well, maybe #84

Please close this issue.
